name: flutter_appauth_web
version: 0.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterAppAuthPlugin
        fileName: flutter_appauth_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.6.2
  flutter_appauth_platform_interface: ^2.0.0


environment:
  sdk: ">=2.8.0 <3.0.0"